site_name: MacServer
theme:
  logo: img/macmini-icon.png
  favicon: img/macmini-icon.png
  name: material
  palette:
      scheme: slate
      primary: blue grey
      accent: indigo
markdown_extensions:
  - attr_list
  - tables
  - attr_list
  - md_in_html
plugins: []